# Setup
title:               Budi Dharmawan
tagline:             'Not really that into art.'
description:         '&ldquo;I am not a consecutive writer.&rdquo; &mdash;Dr. Seuss'
url:                 https://budidharmawan.com
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Budi Dharmawan
  url:               https://budidharmawan.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0