title: Budi Dharmawan
subtitle: A.K.A. BUBS
description: Brown eyes, deuteranomalic. Oh the irony.
author: Budi Dharmawan
timezone: Asia/Jakarta
url: "https://budidharmawan.com"
twitter: budi
github: budi
year: 2016-2019

permalink: /:year/:month/:day/:title.html
excerpt_separator: "<!-- more -->"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
